### ISSUE TITLE
How does NPTv6 handle neighbor request packets for translated addresses

### ISSUE THREAD

**Issue by liusongming-cn** [bu7cher/ixl_unlock#1]
@Andrey V. Elsukov Transplant FreeBsd NPTV6,Prefixes can be converted normally.But Before the data is sent back , the superior will send a neighbor message to query the converted address.In nptv6 module,No processing is seen for these neighbor packets,Is there any specific processing in the protocol stack or other modules.I also need to configure additional modules？

**Comment by bu7cher** [comment]
The question is not related to the project.

Ps. No, L2 processing is done in the generic IPv6 stack, NPTv6 translation is done in-place - packets after translation are going further trough IPv6 stack, i.e via basic routing.
